<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Remove="NewFolder\**" />
    <EmbeddedResource Remove="NewFolder\**" />
    <None Remove="NewFolder\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Data\Configurations\GroupBuyingRequestConfiguration.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kindi.API.Application\Kindi.API.Application.csproj" />
    <ProjectReference Include="..\Kindi.API.Domain\Kindi.API.Domain.csproj" />
    <ProjectReference Include="..\Kindi.API.Shared\Kindi.API.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="Microsoft.AspNetCore.Http" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Data\Configurations\GroupBuyingRequestConfiguration.cs" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>

